repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black --no-color --check
        language: system
        types: [python]
        require_serial: true  # Otherwise the hook will run multiple times
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        require_serial: true  # Otherwise the hook will run multiple times 
